//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorillaChimpDataJamWF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gorillas2Entities : DbContext
    {
        public Gorillas2Entities()
            : base("name=Gorillas2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HabEncounter> HabEncounters { get; set; }
        public virtual DbSet<HabNest> HabNests { get; set; }
        public virtual DbSet<HabObservation> HabObservations { get; set; }
        public virtual DbSet<HabScan> HabScans { get; set; }
    }
}
