//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorillaChimpDataJamWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabNest
    {
        public short UNIQUE_LINE { get; set; }
        public string DATA_SHEET { get; set; }
        public Nullable<short> TALLY { get; set; }
        public string UNIQUE_CONTACT_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string OBSERVER { get; set; }
        public Nullable<short> YEAR { get; set; }
        public string MONTH { get; set; }
        public Nullable<short> DAY { get; set; }
        public Nullable<short> NEST_NUMBER { get; set; }
        public string LOCATION { get; set; }
        public string DUNG_PRESENT { get; set; }
        public string SAMPLE_ID { get; set; }
        public string NEST_TYPE { get; set; }
        public string FOREST_TYPE_CODE { get; set; }
        public string FOREST_TYPE { get; set; }
        public string UNDERSTOREY { get; set; }
        public string CANOPY { get; set; }
        public string NEST_AGE { get; set; }
        public Nullable<short> SITE_SIZE { get; set; }
        public string COMMENT { get; set; }
    }
}
