//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorillaChimpDataJamWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabObservation
    {
        public short UNIQUE_LINE { get; set; }
        public string DATA_ENTRY { get; set; }
        public Nullable<short> TALLY { get; set; }
        public Nullable<short> FIRST_CONTACT_POINT { get; set; }
        public string DATA_SET { get; set; }
        public string SPECIES { get; set; }
        public string UNIQUE_CONTACT_ID { get; set; }
        public string OBSERVER { get; set; }
        public string TRACKER { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string MONTH { get; set; }
        public Nullable<short> DAY { get; set; }
        public Nullable<short> YEAR { get; set; }
        public string C_COMMUNITY_ { get; set; }
        public string C_DETECTION_1_ { get; set; }
        public string C_DETECTION_2_ { get; set; }
        public string LAT { get; set; }
        public string LONG { get; set; }
        public string C_FOREST_TYPE_CODE_ { get; set; }
        public string FOREST_TYPE { get; set; }
        public string UNDERSTOREY { get; set; }
        public string CANOPY { get; set; }
        public string START_TIME { get; set; }
        public string END_TIME { get; set; }
        public string DURATION { get; set; }
        public string HOURS { get; set; }
        public string MIN { get; set; }
        public string TOTAL_DURATION { get; set; }
        public string C_RESPONSE_1_ { get; set; }
        public string RESPONSE_2 { get; set; }
        public string END_CONTACT { get; set; }
        public string TYPE_GROUP { get; set; }
        public string GROUP_ID { get; set; }
        public string CONTACT_NMBR { get; set; }
        public string DISTANCE_HUMANS_M { get; set; }
        public string TOTAL { get; set; }
        public string C_ORIGINAL_PARTY_SIZE_ { get; set; }
        public string NEW_ARRIVALS { get; set; }
        public string AM_GOR_OBS { get; set; }
        public string AF_GOR_OBS { get; set; }
        public Nullable<short> SM_GOR_OBS { get; set; }
        public Nullable<short> SF_GOR_OBS { get; set; }
        public Nullable<short> JV_GOR_OBS { get; set; }
        public Nullable<short> INF_GOR_OBS { get; set; }
        public Nullable<short> UK_GOR_OBS { get; set; }
        public string WEATHER { get; set; }
        public string COMMENTS { get; set; }
        public string INITIAL_LOCATION { get; set; }
        public string NEST_TOTAL { get; set; }
        public string NEST_AGE { get; set; }
    }
}
