//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GorillaChimpDataJamWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabObservation
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public short UNIQUE_LINE { get; set; }

        public string DATA_SHEET { get; set; }
        public string UNIQUE_ENCOUNTER_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<short> YEAR { get; set; }
        public string MONTH { get; set; }
        public Nullable<short> DAY { get; set; }
        public string HOUR { get; set; }
        public string BEHAVIOR { get; set; }
        public string INDIVIDUAL { get; set; }
        public string COMMENT { get; set; }
    }
}
