//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorillaChimpDataJamWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabScan
    {
        public short C_UNIQUE_LINE_ { get; set; }
        public string C_DATA_SHEET_ { get; set; }
        public Nullable<short> TALLY { get; set; }
        public string C_ENCOUNTER_ { get; set; }
        public string C_OBSERVER_ { get; set; }
        public string C_APE_SPECIES_ { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<short> DAY { get; set; }
        public string MONTH { get; set; }
        public Nullable<short> YEAR { get; set; }
        public Nullable<short> HOUR { get; set; }
        public Nullable<short> MINUTE { get; set; }
        public string LOCATION { get; set; }
        public Nullable<short> SCAN_PARTY_SIZE { get; set; }
        public Nullable<short> IN_AM { get; set; }
        public Nullable<short> IN_AF { get; set; }
        public Nullable<short> IN_AD { get; set; }
        public Nullable<short> IN_SAM { get; set; }
        public Nullable<short> IN_SAF { get; set; }
        public Nullable<short> IN_SA { get; set; }
        public Nullable<short> IN_JUVM { get; set; }
        public string IN_JUVF { get; set; }
        public Nullable<short> IN_JUV { get; set; }
        public Nullable<short> IN_INF { get; set; }
        public Nullable<short> IN_UK { get; set; }
        public string NEST { get; set; }
        public string IN_TOT { get; set; }
        public Nullable<short> FD_AM { get; set; }
        public Nullable<short> FD_AF { get; set; }
        public Nullable<short> FD_SAM { get; set; }
        public Nullable<short> FD_SAF { get; set; }
        public string FD_SA { get; set; }
        public Nullable<short> FD_JUVM { get; set; }
        public Nullable<short> FD_JUVF { get; set; }
        public Nullable<short> FD_JUV { get; set; }
        public Nullable<short> FD_INF { get; set; }
        public Nullable<short> FD_UK { get; set; }
        public string FDTOTAL { get; set; }
        public string LOCAL_NAME { get; set; }
        public string SCIENTIFIC_NAME { get; set; }
        public string PART { get; set; }
        public string SIMPLE_PART { get; set; }
        public string FDNOTE { get; set; }
        public Nullable<short> TR_AM { get; set; }
        public Nullable<short> TR_AF { get; set; }
        public Nullable<short> TR_SAM { get; set; }
        public Nullable<short> TR_SAF { get; set; }
        public Nullable<short> TR_SA { get; set; }
        public Nullable<short> TR_JUVM { get; set; }
        public Nullable<short> TR_JUVF { get; set; }
        public Nullable<short> TR_JUV { get; set; }
        public Nullable<short> TR_INF { get; set; }
        public Nullable<short> TR_UK { get; set; }
        public string TR_TOT { get; set; }
        public Nullable<short> OT_AM { get; set; }
        public Nullable<short> OT_AF { get; set; }
        public Nullable<short> OT_SAM { get; set; }
        public string OT_SAF { get; set; }
        public string OT_SA { get; set; }
        public Nullable<short> OT_JUVM { get; set; }
        public string OT_JUVF { get; set; }
        public string OT_JUV { get; set; }
        public Nullable<short> OT_INF { get; set; }
        public string OT_UK { get; set; }
        public string OT_TOT { get; set; }
        public string OTHER_BEHAVIOR { get; set; }
        public string OBJECT { get; set; }
        public string ACTIVITY { get; set; }
        public string SO_AM { get; set; }
        public Nullable<short> SO_AF { get; set; }
        public Nullable<short> SO_SAM { get; set; }
        public string SO_SAF { get; set; }
        public string SO_SA { get; set; }
        public Nullable<short> SO_JUVM { get; set; }
        public string SO_JUVF { get; set; }
        public string SO_JUV { get; set; }
        public Nullable<short> SO_INF { get; set; }
        public string SO_UK { get; set; }
        public string SO_TOT { get; set; }
        public string SOCIAL { get; set; }
        public string INDIVIDUAL { get; set; }
        public string RECIPROCITY { get; set; }
        public string OOV_AM { get; set; }
        public Nullable<short> OOV_AF { get; set; }
        public Nullable<short> OOV_SAM { get; set; }
        public Nullable<short> OOV_SAF { get; set; }
        public string OOV_SA { get; set; }
        public Nullable<short> OOV_JUVM { get; set; }
        public Nullable<short> OOV_JUVF { get; set; }
        public Nullable<short> OOV_JUV { get; set; }
        public Nullable<short> OOV_INF { get; set; }
        public Nullable<short> OOV_UK { get; set; }
        public string OOV_TOT { get; set; }
        public string COMMENT { get; set; }
    }
}
